### ISSUE TITLE
Create a user page

### ISSUE THREAD

**Issue by RazvanSoos** [Franck851/SOEN341#10]
Create a user page in HTML or PHP

Have a box for user information about himself/interests
Have an age
Have an occupation
Have the possibility to add a picture or choose a default one
Have a button for daytime/nighttime mode

**Comment by lkadian** [comment]
I created the html for the account page, where the user can see his own posts, and delete them if he wants. We should also create a html page for the user setting's, where he can change his password, and other account settings.

**Comment by RazvanSoos** [comment]
Did the user settings, I'll modify things as needed, closing the issue
