### ISSUE TITLE
Retrieving question data for home feed using PHP

### ISSUE THREAD

**Issue by laurawheatley** [Franck851/SOEN341#26]
- Issue for "Create the body template section in PHP Issue #4"
- Pulling question data from most recent to least recent from MySQL database in PHP
- Deciding on the size of the output (10 top most recent OR all in descending order?)

**Comment by laurawheatley** [comment]
Assigning size of task

**Comment by laurawheatley** [comment]
TO DO: FIx error " Connection failed: Access denied for user 'heapflow'@'132.205.229.203' " @PetiaPav @Franck851

**Comment by PetiaPav** [comment]
After problems encountered with PHP, we changed to Python
