### ISSUE TITLE
Filling database tables with required fields retrieved from the website

### ISSUE THREAD

**Issue by PetiaPav** [Franck851/SOEN341#28]
- Issue for "Create the body template section in PHP Issue #4"
- Sending information to the database tables whenever user asks a question. View the SQL_Schema.png file for details of the established relations.

**Comment by laurawheatley** [comment]
- adding a request.php page which will take in the user's data and their question and put that into the database (eventually will also have a function for putting user ANSWERS into the database as well)
- deciding how to package our data and send it to our PHP function to be passed to MySQL.
