### ISSUE TITLE
MySQL connection string problem investigation

### ISSUE THREAD

**Issue by Franck851** [Franck851/SOEN341#30]
Try to find why we cannot connect the backend with the MySQL database

**Comment by PetiaPav** [comment]
@Franck851 
Hey, I tried a number of things to solve the 1045 error that we get, after some research.
In the end, I think that I figured out the problem. I believe that the goDaddy account plan we have does not allow for a direct connection to be made to the database. The way @laurawheatley and I were trying to do it was locally, hence it was trying to connect to the local server. 

Therefore, I believe we need to FTP the files, in some directory, directly on goDaddy to run it from there. 
I'm not familiar with how this all works and do not want to risk the security of the website, therefore, does the explanation make sense and if so, could you explain a little in which folder and what way we should upload the file (with PHP and HTML code) be uploaded and ran?

Thank you!
I'll keep looking up more info and if I figure it out, i'll comment again with the solution.

**Comment by PetiaPav** [comment]
Connection has been made. SUCCESS!
