### ISSUE TITLE
Implement Answer Accepting

### ISSUE THREAD

**Issue by laurawheatley** [Franck851/SOEN341#47]
- Allowing a user to accept an answer.
- Only the user who asked the question has the authority to accept.
- When an answer is accepted, it will show either a check mark or a green box.

**Comment by PetiaPav** [comment]
Notes on the task
[SOEN 341 - task.txt](https://github.com/Franck851/SOEN341/files/1819971/SOEN.341.-.task.txt)

**Comment by Franck851** [comment]
I've completed the connection to the database.
